////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/).

SPDX-License-Identifier: CC-BY-4.0
////

[#resources]
== Annex B. Resources

The following resources are available to help develop SMT specifications.
Resources with heading backslash refer to the IDTA Teams drive.

.Resources used in the document
[[table-resources-used-in-the-document]]
[width="99%",cols="12%,88%",options="header",]
|===
|Resource |Description

|[[res1,&#91;R1&#93;]] [R1] a|
Process Description. Registration of Asset Administration Shell Submodel templates for Digital Twins. Industrial Digital Twin Association (IDTA). V1.0

https://industrialdigitaltwin.org/en/wp-content/uploads/sites/2/2022/01/2021-12-01_IDTA_Process-Submodels_V1.0.pdf

|[[res2,&#91;R2&#93;]] [R2] a|
IDTA comments template

\IDTA - WG2 - Submodels\Submodel-Development\00_Templates\03 IDTA Submodel Spec Comments Template.xlsx

|[[res3,&#91;R3&#93;]] [R3] a|
AASX Package Explorer

https://github.com/eclipse-aaspe/aaspe/releases

Previous releases can be found here:

https://github.com/admin-shell-io/aasx-package-explorer/releases

|[[res4,&#91;R4&#93;]] [R4] a|
IDTA GitHub Asset Administration Shell Identifiers

https://github.com/admin-shell-io/id

|[[res5,&#91;R5&#93;]] [R5] a|
Help file for <<res3>> to import/ export tables

https://github.com/eclipse-aaspe/aaspe/tree/main/src/AasxPluginExportTable/help

|[[res6,&#91;R6&#93;]] [R6] a|
Predefined concepts for AASX Package Explorer

https://github.com/eclipse-aaspe/aaspe/tree/main/src/AasxPredefinedConcepts

|[[res7,&#91;R7&#93;]] [R7] a|
PlantUML

https://plantuml.io

|[[res8,&#91;R8&#93;]] [R8] a|
ISO/IEC 19505-2:2012, Information technology — Object Management Group Unified Modeling Language (OMG UML) — Part 2: Superstructure

|[[res9,&#91;R9&#93;]] [R9] a|
Semantic Aspect Meta Model (SAMM)

https://eclipse-esmf.github.io/samm-specification/snapshot/index.html

https://projects.eclipse.org/projects/dt.esmf

|[[res10,&#91;R10&#93;]] [R10] a|
Homepage: “AsciiDoc”.

https://asciidoc.org

|[[res11,&#91;R11&#93;]] [R11] a|
IDTA GitHub repository for Submodel templates.

https://github.com/admin-shell-io/submodel-templates

|[[res12,&#91;R12&#93;]] [R12] a|
AsciiDoc tools:

https://docs.asciidoctor.org

https://pandoc.org

https://docs.asciidoctor.org/asciidoctor/latest/migrate/ms-word/

https://www.vertopal.com/en/convert/docx-to-asciidoc

https://tableconvert.com/asciidoc-generator

|[[res13,&#91;R13&#93;]] [R13] a|
AsciiDoc templates, header & style files for SMT specifications.

https://industrialdigitaltwin.sharepoint.com/:f:/r/sites/IDTA-SubmodelsPrivateTrack/Freigegebene%20Dokumente/Workstream%20%E2%80%9EProcess%E2%80%9C/02%20Best%20practice%20How%20to%20write%20a%20SMT/AsciiDoc_Template_files?csf=1&web=1&e=oPW0cy

Convert Word to AsciiDoc:

https://github.com/admin-shell-io/word2asciidoc

|[[res14,&#91;R14&#93;]] [R14] a|
Command lines for docker containers for rendering AsciiDoc to HTML / PDF (using some of the files in <<res13>>):

For HTML:

[source,bash,linenums]
----
docker run -it -v .:/documents/ asciidoctor/docker-asciidoctor asciidoctor -r asciidoctor-diagram -a toc=left -a stylesheet=asciidoc-style-idta.css *.adoc
----

For PDF with line numbers:

[source,bash,linenums]
----
docker run -it -v .:/documents/ asciidoctor/docker-asciidoctor asciidoctor-pdf -r asciidoctor-diagram -r ./extended.rb -a toc=macro -a pdf-theme=my-theme.yml -a env-pdf *.adoc
----
|===
