[resources]
== Resources

The following resources are available to help develop SMT specifications. Resources with heading backslash refer to the IDTA Teams drive.

[#res1]
[R1] Process Description. Registration of Asset Administration Shell Submodel templates for Digital Twins. Industrial Digital Twin Association (IDTA). V1.0. +
Available: link:https://industrialdigitaltwin.org/en/wp-content/uploads/sites/2/2022/01/2021-12-01_IDTA_Process-Submodels_V1.0.pdf[]

[#res2]
[R2] IDTA comments template. +
Location: `\IDTA - WG2 - Submodels\Submodel-Development\00_Templates\03 IDTA Submodel Spec Comments Template.xlsx`

[#res3]
[R3] AASX Package Explorer. +
Available: link:https://github.com/eclipse-aaspe/aaspe/releases[] +
(Previous releases: link:https://github.com/admin-shell-io/aasx-package-explorer/releases[])

[#res4]
[R4] IDTA GitHub Asset Administration Shell Identifiers. +
Available: link:https://github.com/admin-shell-io/id[]

[#res5]
[R5] Help file for [R3] to import/export tables. +
Available: link:https://github.com/eclipse-aaspe/aaspe/tree/main/src/AasxPluginExportTable/help[]

[#res6]
[R6] Predefined concepts for AASX Package Explorer. +
Available: link:https://github.com/eclipse-aaspe/aaspe/tree/main/src/AasxPredefinedConcepts[]

[#res7]
[R7] PlantUML. +
Available: link:https://plantuml.io[]

[#res8]
[R8] ISO/IEC 19505-2:2012, Information technology — Object Management Group Unified Modeling Language (OMG UML) — Part 2: Superstructure.

[#res9]
[R9] Semantic Aspect Meta Model (SAMM). +
Available: link:https://eclipse-esmf.github.io/samm-specification/snapshot/index.html[] +
(Project home: link:https://projects.eclipse.org/projects/dt.esmf[])

[#res10]
[R10] AsciiDoc Homepage. +
Available: link:https://asciidoc.org/[]

[#res11]
[R11] IDTA GitHub repository for Submodel templates. +
Available: link:https://github.com/admin-shell-io/submodel-templates[]

[#res12]
[R12] AsciiDoc tools: +
* link:https://docs.asciidoctor.org/[]
* link:https://pandoc.org/[]
* link:https://docs.asciidoctor.org/asciidoctor/latest/migrate/ms-word/[]
* link:https://www.vertopal.com/en/convert/docx-to-asciidoc[]
* link:https://tableconvert.com/asciidoc-generator[]

[#res13]
[R13] AsciiDoc templates, header & style files for SMT specifications. +
Available: link:https://industrialdigitaltwin.sharepoint.com/:f:/r/sites/IDTA-SubmodelsPrivateTrack/Freigegebene%20Dokumente/Workstream%20%E2%80%9EProcess%E2%80%9C/02%20Best%20practice%20How%20to%20write%20a%20SMT/AsciiDoc_Template_files?csf=1&web=1&e=oPW0cy[] +
Word to AsciiDoc converter: link:https://github.com/admin-shell-io/word2asciidoc[]

[#res14]
[R14] Command lines for docker containers for rendering AsciiDoc to HTML / PDF (using files in xref:annex/resource.adoc#res13[[R13\]]): +
* HTML: `docker run -it -v .:/documents/ asciidoctor/docker-asciidoctor asciidoctor -r asciidoctor-diagram -a toc=left -a stylesheet=asciidoc-style-idta.css *.adoc` +
* PDF with line numbers: `docker run -it -v .:/documents/ asciidoctor/docker-asciidoctor asciidoctor-pdf -r asciidoctor-diagram -r ./extended.rb -a toc=macro -a pdf-theme=my-theme.yml -a env-pdf *.adoc`
